using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;

namespace PacketGenerator
{
    internal sealed class TypeInfo
    {
        public readonly string IdlName;
        public readonly string CppType;
        public readonly string CsType;
        public readonly string CsWrite;
        public readonly string CsRead;
        public readonly int Size;
        public readonly long MaxValue;

        public TypeInfo(string idlName, string cppType, string csType, string csWrite, string csRead, int size, long maxValue)
        {
            IdlName = idlName;
            CppType = cppType;
            CsType = csType;
            CsWrite = csWrite;
            CsRead = csRead;
            Size = size;
            MaxValue = maxValue;
        }
    }

    internal sealed class ProtocolSettings
    {
        public int PacketCode = -1;
        public TypeInfo PacketTypeType;
        public TypeInfo PayloadSizeType;
        public int MaxPayloadSize = -1;

        public int HeaderSize
        {
            get { return 1 + PayloadSizeType.Size + PacketTypeType.Size; }
        }

        public string PacketCodeHex
        {
            get { return "0x" + PacketCode.ToString("X2", CultureInfo.InvariantCulture); }
        }
    }

    internal sealed class FieldDef
    {
        public string TypeName;
        public string Name;
        public TypeInfo Type;
        public bool AutoGenerated;
    }

    internal sealed class ConstDef
    {
        public string TypeName;
        public string Name;
        public TypeInfo Type;
        public long Value;
    }

    internal sealed class PacketDef
    {
        public string Direction;
        public string Name;
        public int Id;
        public readonly List<FieldDef> DeclaredFields = new List<FieldDef>();
        public readonly List<FieldDef> WireFields = new List<FieldDef>();

        public bool IsC2S { get { return Direction == "c2s"; } }
        public bool IsS2C { get { return Direction == "s2c"; } }
        public string DirectionUpper { get { return Direction.ToUpperInvariant(); } }
        public string NameUpper { get { return TextUtil.ToSnakeUpper(Name); } }
        public string Symbol { get { return DirectionUpper + "_" + NameUpper; } }

        public int PayloadSize
        {
            get
            {
                int size = 0;
                for (int i = 0; i < WireFields.Count; ++i)
                    size += WireFields[i].Type.Size;
                return size;
            }
        }
    }

    internal sealed class ProtocolDef
    {
        public readonly ProtocolSettings Settings = new ProtocolSettings();
        public readonly List<ConstDef> Constants = new List<ConstDef>();
        public readonly List<PacketDef> Packets = new List<PacketDef>();

        public List<PacketDef> GetPackets(string direction)
        {
            List<PacketDef> result = new List<PacketDef>();
            for (int i = 0; i < Packets.Count; ++i)
            {
                if (Packets[i].Direction == direction)
                    result.Add(Packets[i]);
            }
            return result;
        }
    }

    internal static class Program
    {
        private const string ServerGameRelativePath = "TCP_FIGHTER/Game";
        private const string ClientGeneratedRelativePath = "Client/Generated/RPC";
        private const string ProtocolRelativePath = "Tools/PacketGenerator/Protocol/GameProtocol.IDL";

        private static readonly Dictionary<string, TypeInfo> Types = CreateTypeMap();

        private static int Main(string[] args)
        {
            try
            {
                string root = PathUtil.FindRoot(ProtocolRelativePath);
                string protocolPath = PathUtil.Combine(root, ProtocolRelativePath);
                string serverRpcPath = Path.Combine(PathUtil.Combine(root, ServerGameRelativePath), "RPC");
                string clientRpcPath = PathUtil.Combine(root, ClientGeneratedRelativePath);

                ProtocolDef protocol = ProtocolParser.Parse(protocolPath, Types);
                ProtocolValidator.Validate(protocol);

                WriteFile(Path.Combine(serverRpcPath, "RPCCommon.h"), CppGenerator.GenerateCommon(protocol));
                WriteFile(Path.Combine(serverRpcPath, "C2S_Stub.h"), CppGenerator.GenerateC2SStub(protocol));
                WriteFile(Path.Combine(serverRpcPath, "S2C_Proxy.h"), CppGenerator.GenerateS2CProxy(protocol));

                WriteFile(Path.Combine(clientRpcPath, "RPCCommon.cs"), CSharpGenerator.GenerateCommon(protocol));
                WriteFile(Path.Combine(clientRpcPath, "C2S_Proxy.cs"), CSharpGenerator.GenerateC2SProxy(protocol));
                WriteFile(Path.Combine(clientRpcPath, "S2C_Stub.cs"), CSharpGenerator.GenerateS2CStub(protocol));

                Console.WriteLine("RPC PacketGenerator completed.");
                Console.WriteLine("Protocol   : " + protocolPath);
                Console.WriteLine("Server RPC : " + serverRpcPath);
                Console.WriteLine("Client RPC : " + clientRpcPath);
                Console.WriteLine("Packet Count: " + protocol.Packets.Count.ToString(CultureInfo.InvariantCulture));
                return 0;
            }
            catch (Exception ex)
            {
                Console.WriteLine("[PacketGenerator Error]");
                Console.WriteLine(ex.Message);
                return 1;
            }
        }

        private static void WriteFile(string path, string text)
        {
            PathUtil.EnsureParentDirectory(path);
            File.WriteAllText(path, text, new UTF8Encoding(false));
        }

        private static Dictionary<string, TypeInfo> CreateTypeMap()
        {
            Dictionary<string, TypeInfo> map = new Dictionary<string, TypeInfo>(StringComparer.Ordinal);
            map.Add("int8", new TypeInfo("int8", "std::int8_t", "sbyte", "WriteInt8", "ReadInt8", 1, 127));
            map.Add("uint8", new TypeInfo("uint8", "std::uint8_t", "byte", "WriteUInt8", "ReadUInt8", 1, 255));
            map.Add("int16", new TypeInfo("int16", "std::int16_t", "short", "WriteInt16", "ReadInt16", 2, 32767));
            map.Add("uint16", new TypeInfo("uint16", "std::uint16_t", "ushort", "WriteUInt16", "ReadUInt16", 2, 65535));
            map.Add("int32", new TypeInfo("int32", "std::int32_t", "int", "WriteInt32", "ReadInt32", 4, 2147483647));
            map.Add("uint32", new TypeInfo("uint32", "std::uint32_t", "uint", "WriteUInt32", "ReadUInt32", 4, long.MaxValue));
            map.Add("int64", new TypeInfo("int64", "std::int64_t", "long", "WriteInt64", "ReadInt64", 8, long.MaxValue));
            map.Add("uint64", new TypeInfo("uint64", "std::uint64_t", "ulong", "WriteUInt64", "ReadUInt64", 8, long.MaxValue));
            map.Add("float", new TypeInfo("float", "float", "float", "WriteFloat", "ReadFloat", 4, long.MaxValue));
            map.Add("double", new TypeInfo("double", "double", "double", "WriteDouble", "ReadDouble", 8, long.MaxValue));
            return map;
        }
    }

    internal static class ProtocolParser
    {
        public static ProtocolDef Parse(string path, Dictionary<string, TypeInfo> types)
        {
            if (!File.Exists(path))
                throw new FileNotFoundException("IDL file not found.", path);

            ProtocolDef protocol = new ProtocolDef();
            string[] lines = File.ReadAllLines(path);
            int currentPacketId = -1;

            for (int i = 0; i < lines.Length; ++i)
            {
                string line = TextUtil.TrimStatement(TextUtil.StripComment(lines[i]));
                if (line.Length == 0)
                    continue;

                if (IsConst(line))
                    protocol.Constants.Add(ParseConst(line, i + 1, types));
                else if (IsSetting(line))
                    ParseSetting(protocol.Settings, line, i + 1, types);
                else
                    protocol.Packets.Add(ParsePacket(line, i + 1, types, ref currentPacketId));
            }

            ApplyS2CAutoId(protocol, types);
            return protocol;
        }

        private static bool IsConst(string line)
        {
            return line.StartsWith("const ", StringComparison.Ordinal);
        }

        private static bool IsSetting(string line)
        {
            return line.IndexOf('=') > 0 && line.IndexOf('(') < 0;
        }

        private static ConstDef ParseConst(string line, int lineNumber, Dictionary<string, TypeInfo> types)
        {
            int equal = line.IndexOf('=');
            if (equal < 0)
                throw new Exception("Line " + lineNumber + ": invalid const declaration.");

            string left = line.Substring(5, equal - 5).Trim();
            string right = line.Substring(equal + 1).Trim();
            string[] parts = TextUtil.SplitByWhiteSpace(left);
            if (parts.Length != 2)
                throw new Exception("Line " + lineNumber + ": expected 'const type NAME = value'.");

            TypeInfo type;
            if (!types.TryGetValue(parts[0], out type))
                throw new Exception("Line " + lineNumber + ": unsupported const type: " + parts[0]);

            if (!TextUtil.IsIdentifier(parts[1]))
                throw new Exception("Line " + lineNumber + ": invalid const name: " + parts[1]);

            long value = TextUtil.ParseLongLiteral(right, lineNumber);
            if (value < 0 || value > type.MaxValue)
                throw new Exception("Line " + lineNumber + ": const value exceeds type range: " + parts[1]);

            ConstDef constant = new ConstDef();
            constant.TypeName = parts[0];
            constant.Name = parts[1];
            constant.Type = type;
            constant.Value = value;
            return constant;
        }

        private static void ParseSetting(ProtocolSettings settings, string line, int lineNumber, Dictionary<string, TypeInfo> types)
        {
            int equal = line.IndexOf('=');
            string key = line.Substring(0, equal).Trim().ToLowerInvariant();
            string value = line.Substring(equal + 1).Trim();

            if (key == "packet_code")
                settings.PacketCode = TextUtil.ParseIntLiteral(value, lineNumber);
            else if (key == "packet_type_type")
                settings.PacketTypeType = ParseTypeSetting(types, value, lineNumber, key);
            else if (key == "payload_size_type")
                settings.PayloadSizeType = ParseTypeSetting(types, value, lineNumber, key);
            else if (key == "max_payload_size")
                settings.MaxPayloadSize = TextUtil.ParseIntLiteral(value, lineNumber);
            else
                throw new Exception("Line " + lineNumber + ": unknown setting: " + key);
        }

        private static TypeInfo ParseTypeSetting(Dictionary<string, TypeInfo> types, string value, int lineNumber, string key)
        {
            TypeInfo type;
            if (!types.TryGetValue(value, out type))
                throw new Exception("Line " + lineNumber + ": unsupported " + key + ": " + value);
            if (value != "uint8" && value != "uint16" && value != "uint32")
                throw new Exception("Line " + lineNumber + ": " + key + " must be uint8, uint16, or uint32.");
            return type;
        }

        private static PacketDef ParsePacket(string line, int lineNumber, Dictionary<string, TypeInfo> types, ref int currentPacketId)
        {
            int split = TextUtil.IndexOfWhiteSpace(line, 0);
            if (split <= 0)
                throw new Exception("Line " + lineNumber + ": expected 'c2s Name(...);' or 's2c Name(...);'.");

            PacketDef packet = new PacketDef();
            packet.Direction = line.Substring(0, split).Trim().ToLowerInvariant();
            if (packet.Direction != "c2s" && packet.Direction != "s2c")
                throw new Exception("Line " + lineNumber + ": direction must be c2s or s2c.");

            string body = line.Substring(split).Trim();
            int open = body.IndexOf('(');
            int close = body.LastIndexOf(')');
            if (open <= 0 || close < open)
                throw new Exception("Line " + lineNumber + ": invalid packet declaration.");

            string left = body.Substring(0, open).Trim();
            int equal = left.IndexOf('=');
            if (equal >= 0)
            {
                packet.Name = left.Substring(0, equal).Trim();
                packet.Id = TextUtil.ParseIntLiteral(left.Substring(equal + 1).Trim(), lineNumber);
                currentPacketId = packet.Id;
            }
            else
            {
                packet.Name = left.Trim();
                currentPacketId = currentPacketId < 0 ? 0 : currentPacketId + 1;
                packet.Id = currentPacketId;
            }

            if (!TextUtil.IsIdentifier(packet.Name))
                throw new Exception("Line " + lineNumber + ": invalid packet name: " + packet.Name);
            if (packet.Id < 0)
                throw new Exception("Line " + lineNumber + ": packet id must be greater than or equal to 0.");

            string args = body.Substring(open + 1, close - open - 1).Trim();
            if (args.Length > 0)
                ParseFields(packet.DeclaredFields, args, lineNumber, types);

            for (int i = 0; i < packet.DeclaredFields.Count; ++i)
                packet.WireFields.Add(packet.DeclaredFields[i]);

            return packet;
        }

        private static void ParseFields(List<FieldDef> output, string args, int lineNumber, Dictionary<string, TypeInfo> types)
        {
            string[] fields = TextUtil.SplitByComma(args);
            for (int i = 0; i < fields.Length; ++i)
                output.Add(ParseField(fields[i].Trim(), i, lineNumber, types));
        }

        private static FieldDef ParseField(string text, int index, int lineNumber, Dictionary<string, TypeInfo> types)
        {
            string[] parts = TextUtil.SplitByWhiteSpace(text);
            if (parts.Length == 0 || parts.Length > 2)
                throw new Exception("Line " + lineNumber + ": invalid field: " + text);

            TypeInfo type;
            if (!types.TryGetValue(parts[0], out type))
                throw new Exception("Line " + lineNumber + ": unsupported type: " + parts[0]);

            string name = parts.Length == 2 ? parts[1] : "arg" + index.ToString(CultureInfo.InvariantCulture);
            if (!TextUtil.IsIdentifier(name))
                throw new Exception("Line " + lineNumber + ": invalid field name: " + name);

            FieldDef field = new FieldDef();
            field.TypeName = parts[0];
            field.Name = name;
            field.Type = type;
            field.AutoGenerated = false;
            return field;
        }

        private static void ApplyS2CAutoId(ProtocolDef protocol, Dictionary<string, TypeInfo> types)
        {
            TypeInfo int32Type = types["int32"];
            for (int i = 0; i < protocol.Packets.Count; ++i)
            {
                PacketDef packet = protocol.Packets[i];
                if (!packet.IsS2C)
                    continue;

                FieldDef id = new FieldDef();
                id.TypeName = "int32";
                id.Name = "id";
                id.Type = int32Type;
                id.AutoGenerated = true;
                packet.WireFields.Insert(0, id);
            }
        }
    }

    internal static class ProtocolValidator
    {
        public static void Validate(ProtocolDef protocol)
        {
            ValidateSettings(protocol.Settings);
            ValidateConstants(protocol);

            Dictionary<int, string> ids = new Dictionary<int, string>();
            HashSet<string> symbols = new HashSet<string>(StringComparer.Ordinal);

            for (int i = 0; i < protocol.Packets.Count; ++i)
            {
                PacketDef p = protocol.Packets[i];

                if (p.Id > protocol.Settings.PacketTypeType.MaxValue)
                    throw new Exception(p.Symbol + ": packet id exceeds packet_type_type range.");

                if (p.PayloadSize > protocol.Settings.MaxPayloadSize)
                    throw new Exception(p.Symbol + ": payload size exceeds max_payload_size.");

                if (p.PayloadSize > protocol.Settings.PayloadSizeType.MaxValue)
                    throw new Exception(p.Symbol + ": payload size exceeds payload_size_type range.");

                string oldSymbol;
                if (ids.TryGetValue(p.Id, out oldSymbol))
                    throw new Exception("Duplicate packet id " + p.Id + ": " + oldSymbol + " / " + p.Symbol);

                if (!symbols.Add(p.Symbol))
                    throw new Exception("Duplicate packet symbol: " + p.Symbol);

                ids.Add(p.Id, p.Symbol);
                ValidateFieldNames(p);
            }
        }

        private static void ValidateConstants(ProtocolDef protocol)
        {
            HashSet<string> names = new HashSet<string>(StringComparer.Ordinal);
            for (int i = 0; i < protocol.Constants.Count; ++i)
            {
                ConstDef c = protocol.Constants[i];
                if (!names.Add(c.Name))
                    throw new Exception("Duplicate const name: " + c.Name);
            }
        }

        private static void ValidateFieldNames(PacketDef packet)
        {
            HashSet<string> names = new HashSet<string>(StringComparer.Ordinal);
            for (int i = 0; i < packet.WireFields.Count; ++i)
            {
                string name = packet.WireFields[i].Name;
                if (!names.Add(name))
                    throw new Exception(packet.Symbol + ": duplicate field name: " + name);
            }
        }

        private static void ValidateSettings(ProtocolSettings s)
        {
            if (s.PacketCode < 0 || s.PacketCode > 255)
                throw new Exception("packet_code must be defined and in range 0~255.");
            if (s.PacketTypeType == null)
                throw new Exception("packet_type_type must be defined.");
            if (s.PayloadSizeType == null)
                throw new Exception("payload_size_type must be defined.");
            if (s.MaxPayloadSize <= 0)
                throw new Exception("max_payload_size must be defined and greater than 0.");
            if (s.MaxPayloadSize > s.PayloadSizeType.MaxValue)
                throw new Exception("max_payload_size exceeds payload_size_type range.");
        }
    }

    internal static class CppGenerator
    {
        public static string GenerateCommon(ProtocolDef protocol)
        {
            CodeWriter w = new CodeWriter();
            w.Line("#pragma once");
            w.Line();
            w.Line("#include <cstdint>");
            w.Line();
            w.Line("constexpr std::uint8_t dfPACKET_CODE = static_cast<std::uint8_t>(" + protocol.Settings.PacketCodeHex + ");");
            w.Line("constexpr int dfPACKET_HEADER_SIZE = " + protocol.Settings.HeaderSize.ToString(CultureInfo.InvariantCulture) + ";");
            w.Line("constexpr int dfPACKET_MAX_PAYLOAD_SIZE = " + protocol.Settings.MaxPayloadSize.ToString(CultureInfo.InvariantCulture) + ";");
            w.Line("constexpr int dfPACKET_MAX_SIZE = dfPACKET_HEADER_SIZE + dfPACKET_MAX_PAYLOAD_SIZE;");
            w.Line("using PacketType = " + protocol.Settings.PacketTypeType.CppType + ";");
            w.Line("using PayloadSizeType = " + protocol.Settings.PayloadSizeType.CppType + ";");
            w.Line();
            AppendConstants(w, protocol);
            w.Line();
            AppendPacketIds(w, protocol);
            w.Line();
            AppendPayloadSizes(w, protocol);
            return w.ToString();
        }

        public static string GenerateC2SStub(ProtocolDef protocol)
        {
            List<PacketDef> packets = protocol.GetPackets("c2s");
            CodeWriter w = new CodeWriter();
            w.Line("#pragma once");
            w.Line();
            w.Line("#include \"RPCCommon.h\"");
            w.Line("#include \"../../Core/SerializationBuffer.h\"");
            w.Line("#include \"../../Core/Session.h\"");
            w.Line();
            w.Line("class IC2S_Handler");
            w.BeginBlock();
            w.Line("public:");
            w.Indent();
            w.Line("virtual ~IC2S_Handler() = default;");
            w.Line();
            for (int i = 0; i < packets.Count; ++i)
                w.Line("virtual bool On" + packets[i].Name + "(CSession* session" + CppParameterList(packets[i].DeclaredFields, false) + ") = 0;");
            w.Unindent();
            w.EndBlock(";");
            w.Line();
            w.Line("class CC2S_Stub");
            w.BeginBlock();
            w.Line("public:");
            w.Indent();
            w.Line("static inline bool Dispatch(IC2S_Handler& handler, CSession* session, CPacket& packet, PacketType packetType)");
            w.BeginBlock();
            w.Line("switch (packetType)");
            w.BeginBlock();
            for (int i = 0; i < packets.Count; ++i)
                AppendC2SDispatchCase(w, packets[i]);
            w.Line("default:");
            w.Indent();
            w.Line("return false;");
            w.Unindent();
            w.EndBlock();
            w.EndBlock();
            w.Unindent();
            w.EndBlock(";");
            return w.ToString();
        }

        public static string GenerateS2CProxy(ProtocolDef protocol)
        {
            List<PacketDef> packets = protocol.GetPackets("s2c");
            CodeWriter w = new CodeWriter();
            w.Line("#pragma once");
            w.Line();
            w.Line("#include \"RPCCommon.h\"");
            w.Line("#include \"../../Core/SerializationBuffer.h\"");
            w.Line("#include \"../../Core/Session.h\"");
            w.Line();
            w.Line("class IS2C_Sender");
            w.BeginBlock();
            w.Line("public:");
            w.Indent();
            w.Line("virtual ~IS2C_Sender() = default;");
            w.Line("virtual bool SendRPCPacket(CSession* session, const CPacket& packet) = 0;");
            w.Unindent();
            w.EndBlock(";");
            w.Line();
            w.Line("class CS2C_Proxy");
            w.BeginBlock();
            w.Line("public:");
            w.Indent();
            w.Line("explicit CS2C_Proxy(IS2C_Sender* sender = nullptr) : m_Sender(sender) {}");
            w.Line("inline void SetSender(IS2C_Sender* sender) { m_Sender = sender; }");
            w.Line();
            for (int i = 0; i < packets.Count; ++i)
            {
                AppendS2CProxyFunction(w, packets[i]);
                w.Line();
            }
            w.Unindent();
            w.Line("private:");
            w.Indent();
            w.Line("IS2C_Sender* m_Sender;");
            w.Unindent();
            w.EndBlock(";");
            return w.ToString();
        }

        private static void AppendConstants(CodeWriter w, ProtocolDef protocol)
        {
            for (int i = 0; i < protocol.Constants.Count; ++i)
            {
                ConstDef c = protocol.Constants[i];
                w.Line("constexpr " + c.Type.CppType + " df" + c.Name + " = static_cast<" + c.Type.CppType + ">(" + c.Value.ToString(CultureInfo.InvariantCulture) + ");");
            }
        }

        private static void AppendPacketIds(CodeWriter w, ProtocolDef protocol)
        {
            for (int i = 0; i < protocol.Packets.Count; ++i)
            {
                PacketDef p = protocol.Packets[i];
                w.Line("constexpr PacketType dfPACKET_" + p.Symbol + " = static_cast<PacketType>(" + p.Id.ToString(CultureInfo.InvariantCulture) + ");");
            }
        }

        private static void AppendPayloadSizes(CodeWriter w, ProtocolDef protocol)
        {
            for (int i = 0; i < protocol.Packets.Count; ++i)
            {
                PacketDef p = protocol.Packets[i];
                w.Line("constexpr PayloadSizeType dfPACKET_PAYLOAD_SIZE_" + p.Symbol + " = static_cast<PayloadSizeType>(" + p.PayloadSize.ToString(CultureInfo.InvariantCulture) + ");");
            }
        }

        private static void AppendC2SDispatchCase(CodeWriter w, PacketDef p)
        {
            w.Line("case dfPACKET_" + p.Symbol + ":");
            w.BeginBlock();
            for (int i = 0; i < p.DeclaredFields.Count; ++i)
            {
                FieldDef f = p.DeclaredFields[i];
                w.Line(f.Type.CppType + " " + f.Name + "{};");
            }
            w.Line();
            for (int i = 0; i < p.DeclaredFields.Count; ++i)
                w.Line("packet >> " + p.DeclaredFields[i].Name + ";");
            w.Line("if (packet.IsError())");
            w.Indent();
            w.Line("return false;");
            w.Unindent();
            w.Line("return handler.On" + p.Name + "(session" + CppArgumentList(p.DeclaredFields) + ");");
            w.EndBlock();
        }

        private static void AppendS2CProxyFunction(CodeWriter w, PacketDef p)
        {
            w.Line("inline bool " + p.Name + "(CSession* session" + CppParameterList(p.WireFields, false) + ")");
            w.BeginBlock();
            w.Line("if (m_Sender == nullptr)");
            w.Indent();
            w.Line("return false;");
            w.Unindent();
            w.Line("CPacket packet;");
            w.Line("packet << dfPACKET_CODE;");
            w.Line("packet << dfPACKET_PAYLOAD_SIZE_" + p.Symbol + ";");
            w.Line("packet << dfPACKET_" + p.Symbol + ";");
            for (int i = 0; i < p.WireFields.Count; ++i)
                w.Line("packet << " + p.WireFields[i].Name + ";");
            w.Line("return m_Sender->SendRPCPacket(session, packet);");
            w.EndBlock();
        }

        private static string CppParameterList(List<FieldDef> fields, bool byRef)
        {
            StringBuilder sb = new StringBuilder();
            for (int i = 0; i < fields.Count; ++i)
            {
                FieldDef f = fields[i];
                sb.Append(", ");
                sb.Append(f.Type.CppType);
                if (byRef)
                    sb.Append("&");
                sb.Append(" ");
                sb.Append(f.Name);
            }
            return sb.ToString();
        }

        private static string CppArgumentList(List<FieldDef> fields)
        {
            StringBuilder sb = new StringBuilder();
            for (int i = 0; i < fields.Count; ++i)
            {
                sb.Append(", ");
                sb.Append(fields[i].Name);
            }
            return sb.ToString();
        }
    }

    internal static class CSharpGenerator
    {
        public static string GenerateCommon(ProtocolDef protocol)
        {
            CodeWriter w = new CodeWriter("    ");
            w.Line("using System;");
            w.Line();
            w.Line("namespace Generated.RPC");
            w.BeginBlock();
            w.Line("public static class RPCCommon");
            w.BeginBlock();
            w.Line("public const byte PacketCode = " + protocol.Settings.PacketCodeHex + ";");
            w.Line("public const int HeaderSize = " + protocol.Settings.HeaderSize.ToString(CultureInfo.InvariantCulture) + ";");
            w.Line("public const int MaxPayloadSize = " + protocol.Settings.MaxPayloadSize.ToString(CultureInfo.InvariantCulture) + ";");
            w.Line("public const int MaxPacketSize = HeaderSize + MaxPayloadSize;");
            w.Line();
            for (int i = 0; i < protocol.Constants.Count; ++i)
                w.Line("public const " + protocol.Constants[i].Type.CsType + " " + protocol.Constants[i].Name + " = " + CSharpLiteral(protocol.Constants[i]) + ";");
            w.Line();
            for (int i = 0; i < protocol.Packets.Count; ++i)
                w.Line("public const " + protocol.Settings.PacketTypeType.CsType + " " + protocol.Packets[i].Symbol + " = " + protocol.Packets[i].Id.ToString(CultureInfo.InvariantCulture) + ";");
            w.Line();
            for (int i = 0; i < protocol.Packets.Count; ++i)
                w.Line("public const " + protocol.Settings.PayloadSizeType.CsType + " PayloadSize_" + protocol.Packets[i].Symbol + " = " + protocol.Packets[i].PayloadSize.ToString(CultureInfo.InvariantCulture) + ";");
            w.Line();
            AppendPrimitiveIO(w);
            w.EndBlock();
            w.EndBlock();
            return w.ToString();
        }

        public static string GenerateC2SProxy(ProtocolDef protocol)
        {
            List<PacketDef> packets = protocol.GetPackets("c2s");
            CodeWriter w = new CodeWriter("    ");
            w.Line("namespace Generated.RPC");
            w.BeginBlock();
            w.Line("public interface IC2S_Sender");
            w.BeginBlock();
            w.Line("bool SendRPCPacket(byte[] packet);");
            w.EndBlock();
            w.Line();
            w.Line("public sealed class C2S_Proxy");
            w.BeginBlock();
            w.Line("private readonly IC2S_Sender _sender;");
            w.Line();
            w.Line("public C2S_Proxy(IC2S_Sender sender)");
            w.BeginBlock();
            w.Line("_sender = sender;");
            w.EndBlock();
            w.Line();
            for (int i = 0; i < packets.Count; ++i)
            {
                AppendC2SProxyFunction(w, protocol, packets[i]);
                w.Line();
            }
            w.EndBlock();
            w.EndBlock();
            return w.ToString();
        }

        public static string GenerateS2CStub(ProtocolDef protocol)
        {
            List<PacketDef> packets = protocol.GetPackets("s2c");
            CodeWriter w = new CodeWriter("    ");
            w.Line("namespace Generated.RPC");
            w.BeginBlock();
            w.Line("public abstract class S2C_Stub");
            w.BeginBlock();
            w.Line("public bool Dispatch(byte[] buffer, int offset, " + protocol.Settings.PacketTypeType.CsType + " packetType)");
            w.BeginBlock();
            w.Line("switch (packetType)");
            w.BeginBlock();
            for (int i = 0; i < packets.Count; ++i)
                AppendS2CDispatchCase(w, packets[i]);
            w.Line("default:");
            w.Indent();
            w.Line("return false;");
            w.Unindent();
            w.EndBlock();
            w.EndBlock();
            w.Line();
            for (int i = 0; i < packets.Count; ++i)
                w.Line("protected abstract bool On" + packets[i].Name + "(" + CsParameterList(packets[i].WireFields, false) + ");");
            w.EndBlock();
            w.EndBlock();
            return w.ToString();
        }

        private static void AppendC2SProxyFunction(CodeWriter w, ProtocolDef protocol, PacketDef p)
        {
            w.Line("public bool " + p.Name + "(" + CsParameterList(p.DeclaredFields, false) + ")");
            w.BeginBlock();
            w.Line("byte[] buffer = new byte[RPCCommon.HeaderSize + RPCCommon.PayloadSize_" + p.Symbol + "];");
            w.Line("int offset = 0;");
            w.Line("RPCCommon.WriteUInt8(buffer, ref offset, RPCCommon.PacketCode);");
            w.Line("RPCCommon." + protocol.Settings.PayloadSizeType.CsWrite + "(buffer, ref offset, RPCCommon.PayloadSize_" + p.Symbol + ");");
            w.Line("RPCCommon." + protocol.Settings.PacketTypeType.CsWrite + "(buffer, ref offset, RPCCommon." + p.Symbol + ");");
            for (int i = 0; i < p.DeclaredFields.Count; ++i)
                w.Line("RPCCommon." + p.DeclaredFields[i].Type.CsWrite + "(buffer, ref offset, " + p.DeclaredFields[i].Name + ");");
            w.Line("return _sender != null && _sender.SendRPCPacket(buffer);");
            w.EndBlock();
        }

        private static void AppendS2CDispatchCase(CodeWriter w, PacketDef p)
        {
            w.Line("case RPCCommon." + p.Symbol + ":");
            w.BeginBlock();
            for (int i = 0; i < p.WireFields.Count; ++i)
                w.Line(p.WireFields[i].Type.CsType + " " + p.WireFields[i].Name + ";");
            w.Line("try");
            w.BeginBlock();
            for (int i = 0; i < p.WireFields.Count; ++i)
            {
                FieldDef f = p.WireFields[i];
                w.Line(f.Name + " = RPCCommon." + f.Type.CsRead + "(buffer, ref offset);");
            }
            w.EndBlock();
            w.Line("catch");
            w.BeginBlock();
            w.Line("return false;");
            w.EndBlock();
            w.Line("return On" + p.Name + "(" + CsArgumentList(p.WireFields) + ");");
            w.EndBlock();
        }

        private static string CsParameterList(List<FieldDef> fields, bool includeOut)
        {
            StringBuilder sb = new StringBuilder();
            for (int i = 0; i < fields.Count; ++i)
            {
                if (i > 0)
                    sb.Append(", ");
                FieldDef f = fields[i];
                if (includeOut)
                    sb.Append("out ");
                sb.Append(f.Type.CsType);
                sb.Append(" ");
                sb.Append(f.Name);
            }
            return sb.ToString();
        }

        private static string CsArgumentList(List<FieldDef> fields)
        {
            StringBuilder sb = new StringBuilder();
            for (int i = 0; i < fields.Count; ++i)
            {
                if (i > 0)
                    sb.Append(", ");
                sb.Append(fields[i].Name);
            }
            return sb.ToString();
        }

        private static string CSharpLiteral(ConstDef constant)
        {
            string value = constant.Value.ToString(CultureInfo.InvariantCulture);
            if (constant.Type.CsType == "uint")
                return value + "u";
            if (constant.Type.CsType == "long")
                return value + "L";
            if (constant.Type.CsType == "ulong")
                return value + "UL";
            return value;
        }

        private static void AppendPrimitiveIO(CodeWriter w)
        {
            w.Line("public static void Require(byte[] buffer, int offset, int size)");
            w.BeginBlock();
            w.Line("if (buffer == null || offset < 0 || size < 0 || offset + size > buffer.Length)");
            w.Indent();
            w.Line("throw new ArgumentOutOfRangeException();");
            w.Unindent();
            w.EndBlock();
            w.Line();
            w.Line("public static void WriteInt8(byte[] buffer, ref int offset, sbyte value) { Require(buffer, offset, 1); buffer[offset++] = unchecked((byte)value); }");
            w.Line("public static void WriteUInt8(byte[] buffer, ref int offset, byte value) { Require(buffer, offset, 1); buffer[offset++] = value; }");
            w.Line("public static void WriteInt16(byte[] buffer, ref int offset, short value) { WriteBytes(buffer, ref offset, BitConverter.GetBytes(value)); }");
            w.Line("public static void WriteUInt16(byte[] buffer, ref int offset, ushort value) { WriteBytes(buffer, ref offset, BitConverter.GetBytes(value)); }");
            w.Line("public static void WriteInt32(byte[] buffer, ref int offset, int value) { WriteBytes(buffer, ref offset, BitConverter.GetBytes(value)); }");
            w.Line("public static void WriteUInt32(byte[] buffer, ref int offset, uint value) { WriteBytes(buffer, ref offset, BitConverter.GetBytes(value)); }");
            w.Line("public static void WriteInt64(byte[] buffer, ref int offset, long value) { WriteBytes(buffer, ref offset, BitConverter.GetBytes(value)); }");
            w.Line("public static void WriteUInt64(byte[] buffer, ref int offset, ulong value) { WriteBytes(buffer, ref offset, BitConverter.GetBytes(value)); }");
            w.Line("public static void WriteFloat(byte[] buffer, ref int offset, float value) { WriteBytes(buffer, ref offset, BitConverter.GetBytes(value)); }");
            w.Line("public static void WriteDouble(byte[] buffer, ref int offset, double value) { WriteBytes(buffer, ref offset, BitConverter.GetBytes(value)); }");
            w.Line();
            w.Line("public static sbyte ReadInt8(byte[] buffer, ref int offset) { Require(buffer, offset, 1); return unchecked((sbyte)buffer[offset++]); }");
            w.Line("public static byte ReadUInt8(byte[] buffer, ref int offset) { Require(buffer, offset, 1); return buffer[offset++]; }");
            w.Line("public static short ReadInt16(byte[] buffer, ref int offset) { Require(buffer, offset, 2); short value = BitConverter.ToInt16(buffer, offset); offset += 2; return value; }");
            w.Line("public static ushort ReadUInt16(byte[] buffer, ref int offset) { Require(buffer, offset, 2); ushort value = BitConverter.ToUInt16(buffer, offset); offset += 2; return value; }");
            w.Line("public static int ReadInt32(byte[] buffer, ref int offset) { Require(buffer, offset, 4); int value = BitConverter.ToInt32(buffer, offset); offset += 4; return value; }");
            w.Line("public static uint ReadUInt32(byte[] buffer, ref int offset) { Require(buffer, offset, 4); uint value = BitConverter.ToUInt32(buffer, offset); offset += 4; return value; }");
            w.Line("public static long ReadInt64(byte[] buffer, ref int offset) { Require(buffer, offset, 8); long value = BitConverter.ToInt64(buffer, offset); offset += 8; return value; }");
            w.Line("public static ulong ReadUInt64(byte[] buffer, ref int offset) { Require(buffer, offset, 8); ulong value = BitConverter.ToUInt64(buffer, offset); offset += 8; return value; }");
            w.Line("public static float ReadFloat(byte[] buffer, ref int offset) { Require(buffer, offset, 4); float value = BitConverter.ToSingle(buffer, offset); offset += 4; return value; }");
            w.Line("public static double ReadDouble(byte[] buffer, ref int offset) { Require(buffer, offset, 8); double value = BitConverter.ToDouble(buffer, offset); offset += 8; return value; }");
            w.Line();
            w.Line("private static void WriteBytes(byte[] buffer, ref int offset, byte[] value)");
            w.BeginBlock();
            w.Line("Require(buffer, offset, value.Length);");
            w.Line("Buffer.BlockCopy(value, 0, buffer, offset, value.Length);");
            w.Line("offset += value.Length;");
            w.EndBlock();
        }
    }

    internal sealed class CodeWriter
    {
        private readonly StringBuilder _builder = new StringBuilder();
        private readonly string _indentText;
        private int _indent;

        public CodeWriter() : this("    ") { }
        public CodeWriter(string indentText) { _indentText = indentText; }
        public void Indent() { ++_indent; }
        public void Unindent() { if (_indent > 0) --_indent; }
        public void BeginBlock() { Line("{"); Indent(); }
        public void EndBlock() { Unindent(); Line("}"); }
        public void EndBlock(string suffix) { Unindent(); Line("}" + suffix); }
        public void Line() { _builder.AppendLine(); }
        public void Line(string text)
        {
            for (int i = 0; i < _indent; ++i)
                _builder.Append(_indentText);
            _builder.AppendLine(text);
        }
        public override string ToString() { return _builder.ToString(); }
    }

    internal static class PathUtil
    {
        public static string FindRoot(string protocolRelativePath)
        {
            DirectoryInfo dir = new DirectoryInfo(AppDomain.CurrentDomain.BaseDirectory);
            while (dir != null)
            {
                if (File.Exists(Combine(dir.FullName, protocolRelativePath)))
                    return dir.FullName;
                dir = dir.Parent;
            }
            throw new Exception("Solution root not found. Expected file: " + protocolRelativePath);
        }
        public static string Combine(string root, string relativePath)
        {
            return Path.Combine(root, relativePath.Replace('/', Path.DirectorySeparatorChar));
        }
        public static void EnsureParentDirectory(string filePath)
        {
            string dir = Path.GetDirectoryName(Path.GetFullPath(filePath));
            if (!string.IsNullOrEmpty(dir) && !Directory.Exists(dir))
                Directory.CreateDirectory(dir);
        }
    }

    internal static class TextUtil
    {
        public static string StripComment(string line)
        {
            int slash = line.IndexOf("//", StringComparison.Ordinal);
            int hash = line.IndexOf('#');
            int cut = -1;
            if (slash >= 0) cut = slash;
            if (hash >= 0 && (cut < 0 || hash < cut)) cut = hash;
            return cut >= 0 ? line.Substring(0, cut) : line;
        }
        public static string TrimStatement(string text)
        {
            text = text.Trim();
            if (text.EndsWith(";", StringComparison.Ordinal))
                text = text.Substring(0, text.Length - 1).Trim();
            return text;
        }
        public static int ParseIntLiteral(string text, int lineNumber)
        {
            long value = ParseLongLiteral(text, lineNumber);
            if (value < int.MinValue || value > int.MaxValue)
                throw new Exception("Line " + lineNumber + ": number is out of int range: " + text);
            return (int)value;
        }

        public static long ParseLongLiteral(string text, int lineNumber)
        {
            long value;
            if (text.StartsWith("0x", StringComparison.OrdinalIgnoreCase))
            {
                if (!long.TryParse(text.Substring(2), NumberStyles.HexNumber, CultureInfo.InvariantCulture, out value))
                    throw new Exception("Line " + lineNumber + ": invalid hex number: " + text);
                return value;
            }
            if (!long.TryParse(text, NumberStyles.Integer, CultureInfo.InvariantCulture, out value))
                throw new Exception("Line " + lineNumber + ": invalid number: " + text);
            return value;
        }
        public static int IndexOfWhiteSpace(string text, int start)
        {
            for (int i = start; i < text.Length; ++i)
            {
                if (char.IsWhiteSpace(text[i])) return i;
            }
            return -1;
        }
        public static string[] SplitByComma(string text)
        {
            List<string> list = new List<string>();
            int start = 0;
            for (int i = 0; i < text.Length; ++i)
            {
                if (text[i] == ',')
                {
                    list.Add(text.Substring(start, i - start));
                    start = i + 1;
                }
            }
            list.Add(text.Substring(start));
            return list.ToArray();
        }
        public static string[] SplitByWhiteSpace(string text)
        {
            List<string> list = new List<string>();
            int i = 0;
            while (i < text.Length)
            {
                while (i < text.Length && char.IsWhiteSpace(text[i])) ++i;
                if (i >= text.Length) break;
                int start = i;
                while (i < text.Length && !char.IsWhiteSpace(text[i])) ++i;
                list.Add(text.Substring(start, i - start));
            }
            return list.ToArray();
        }
        public static bool IsIdentifier(string text)
        {
            if (string.IsNullOrEmpty(text)) return false;
            if (!(char.IsLetter(text[0]) || text[0] == '_')) return false;
            for (int i = 1; i < text.Length; ++i)
            {
                char ch = text[i];
                if (!(char.IsLetterOrDigit(ch) || ch == '_')) return false;
            }
            return true;
        }
        public static string ToSnakeUpper(string text)
        {
            StringBuilder b = new StringBuilder();
            for (int i = 0; i < text.Length; ++i)
            {
                char ch = text[i];
                if (char.IsUpper(ch) && i > 0)
                {
                    char prev = text[i - 1];
                    if (char.IsLower(prev) || char.IsDigit(prev)) b.Append('_');
                }
                b.Append(char.ToUpperInvariant(ch));
            }
            return b.ToString();
        }
    }
}
