packet_code = 0x89;
packet_type_type = uint8;
payload_size_type = uint8;
max_payload_size = 255;

const uint8 PACKET_MOVE_DIR_LL = 0;
const uint8 PACKET_MOVE_DIR_LU = 1;
const uint8 PACKET_MOVE_DIR_UU = 2;
const uint8 PACKET_MOVE_DIR_RU = 3;
const uint8 PACKET_MOVE_DIR_RR = 4;
const uint8 PACKET_MOVE_DIR_RD = 5;
const uint8 PACKET_MOVE_DIR_DD = 6;
const uint8 PACKET_MOVE_DIR_LD = 7;

s2c CreateMyCharacter(uint8 direction, int16 x, int16 y, uint8 hp);
s2c CreateOtherCharacter(uint8 direction, int16 x, int16 y, uint8 hp);
s2c DeleteCharacter();

c2s MoveStart = 10(uint8 direction, int16 x, int16 y);
s2c MoveStart(uint8 direction, int16 x, int16 y);

c2s MoveStop = 12(uint8 direction, int16 x, int16 y);
s2c MoveStop(uint8 direction, int16 x, int16 y);

c2s Attack1 = 20(uint8 direction, int16 x, int16 y);
s2c Attack1(uint8 direction, int16 x, int16 y);

c2s Attack2 = 22(uint8 direction, int16 x, int16 y);
s2c Attack2(uint8 direction, int16 x, int16 y);

c2s Attack3 = 24(uint8 direction, int16 x, int16 y);
s2c Attack3(uint8 direction, int16 x, int16 y);

s2c Damage = 30(int32 damageId, uint8 damageHp);

c2s Sync = 250(int16 x, int16 y);
s2c Sync(int16 x, int16 y);
